### ISSUE TITLE
Move bundle to supported version of library

### ISSUE THREAD

**Issue by alek13** [nexylan/slack-bundle#20]
Hi @Soullivaneuh .

As you already know `maknz/slack` repo [was abandoned](https://github.com/maknz/slack/commit/89ff7b2a75379a326f48f3db839912f38511a44e#diff-04c6e90faac2675aa89e2176d2eec7d8R7).
I create a fork [alek13/slack](https://github.com/alek13/slack) & will support this great package for open source community.
I will store namespaces and classes names for backward compatibility (until 3.0).

It would be grateful to move your bundle to use this new package.

**Comment by Soullivaneuh** [comment]
Hi @alek13,

We already the fork work on this repository: https://github.com/nexylan/slack and prepared the issue list. It will be easier to maintain both on the same namespace IMO.

I'll rush the migration normally this month. Maybe would you like to move your efforts on this namespace? :-) We already have some issues on the list: https://github.com/nexylan/slack

**Comment by Soullivaneuh** [comment]
Nexylan namespace migration done on v1.1.1.
