### ISSUE TITLE
minimum php version requirement conflicts with Symfony 3|4

### ISSUE THREAD

**Issue by adombrovsky** [nexylan/slack-bundle#38]
In the version 2.2.1 you bumped min php version to 7.3. Therefore it's not possible to use this bundle with Symfony 3.* and 4.*, because they have lower min supported php version

**Comment by soullivaneuh** [comment]
Stop me if I'm wrong, but Symfony 3.4 [does support php 7.3](https://packagist.org/packages/symfony/symfony#v3.4.37) as well as [Symfony 4](https://packagist.org/packages/symfony/symfony#v4.4.4).

Could you please copy/paste your current `composer.json` file? Maybe I can help you.

**Comment by adombrovsky** [comment]
> Stop me if I'm wrong, but Symfony 3.4 [does support php 7.3](https://packagist.org/packages/symfony/symfony#v3.4.37) as well as [Symfony 4](https://packagist.org/packages/symfony/symfony#v4.4.4).
> 
> Could you please copy/paste your current `composer.json` file? Maybe I can help you.

Yes, they have support for 7.3. The min supported version for Symfony 3/4 is 7.1.3, therefore all projects, with version >=7.1.3 and <7.3 are not able to use latest version 2.2.1

**Comment by soullivaneuh** [comment]
> The min supported version for Symfony 3/4 is 7.1.3

I agree, but we don't strictly follow the Symfony rules about PHP support. We don't have enough resources for that.

Plus, PHP 7.1 is deprecated since a while now.

All I can suggest to you is yo upgrade your PHP version, or stay with an older version of the bundle.

Regards.
