### ISSUE TITLE
Use PSR-17 and PSR-18

### ISSUE THREAD

**Issue by coudenysj** [nexylan/slack-bundle#39]
What can I do to support https://github.com/nexylan/slack/pull/55 here?

**Comment by soullivaneuh** [comment]
Hi @coudenysj,

What do you mean by supporting it? What is your issue exactly?

**Comment by coudenysj** [comment]
Looks like the required version of httplug does not implement the ClientInterface.

I'll try to debug a bit more.

**Comment by coudenysj** [comment]
This should've fixed it (https://github.com/nexylan/slack-bundle/commit/783190b43e8a15a79cb9bc4b768bfbaecb297c15#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780), but looks like my version has conflicts.

It's a application error, sorry for the noise!

**Comment by soullivaneuh** [comment]
Thanks! Related to https://github.com/nexylan/slack-bundle/pull/37
